In [7]:
import pandas as pd

# Load the Excel file
file_path = r"D:\data\Tybsc.xlsx"  # Replace with your file path
df = pd.read_excel(file_path)

# Display a sample of the data for debugging
print("Original Data Sample:")
print(df.head())

# Ensure Pincode column is treated as integers
if df['PINCODE'].dtype != 'int64':  # Convert to integers if needed
    df['PINCODE'] = pd.to_numeric(df['PINCODE'], errors='coerce', downcast='integer')

# Hardcoded pincodes for testing (replace with user input if needed)
user_input = "400706, 410210, 410206, 400709, 00701, 400708"
pincode_list = [int(pincode.strip()) for pincode in user_input.split(',')]  # Convert user input to integers

# Debug: Display Pincode List
print("Pincode List:")
print(pincode_list)

# Filter the data
filtered_df = df[df['PINCODE'].isin(pincode_list)]

# Debug: Display Filtered Data
print("\nFiltered Data Sample:")
print(filtered_df.head())

# Check if filtered data is empty
if filtered_df.empty:
    print("No matching data found for the provided pincodes.")
else:
    # Save to a new Excel file
    output_file = r"D:\data\filtered_data.xlsx"
    filtered_df.to_excel(output_file, index=False, engine='openpyxl')  # Specify the engine explicitly
    print(f"\nFiltered data saved to: {output_file}")

Original Data Sample:
                                      INSTITUTE NAME             STUDENT NAME  \
0  Abasaheb Marathe Arts & New Commerce, Science ...     BENKAR YATNIK VISHAL
1  Abasaheb Marathe Arts & New Commerce, Science ...  HIREMATH ASMITA SHANKAR
2  Abasaheb Marathe Arts & New Commerce, Science ...        JOSHI VIVEK VIKAS
3  Abasaheb Marathe Arts & New Commerce, Science ...       KAJAVE KIRAN SUNIL
4  Abasaheb Marathe Arts & New Commerce, Science ...      KAMBALI SAIL SANDIP

   GENDER                                ADDRESS   PINCODE      MOBILE  \
0    Male            Ogalewadi Ogalewadi Rajapur  416702.0  9022282591
1  Female                AT HATIVALE POST KONDYE  416702.0  7083852334
2    Male  PAHILI WADI AT TAMHANE  POST SOLIVADE  416704.0  8010942179
3    Male                  Mithgawane Mithgawane  416702.0  9356248272
4    Male                  Kasabawadi Mithgawane  416702.0  8767684109

                        EMAIL    COURSE  \
0      yatnikbenkar@gmail.com  T.Y.B.Sc
1  asmitahiremath25@gmail.com  T.Y.B.Sc
2        jovivek338@gmail.com  T.Y.B.Sc
3     kirankajave67@gmail.com  T.Y.B.Sc
4     kamblisail273@gmail.com  T.Y.B.Sc

                                          SUBJECT 1 SUBJECT 2  \
0      Chemistry : Practical of USCH501 and USCH502   USCHP06
1      Chemistry : Practical of USCH501 and USCH502   USCHP06
2  Botany : Practicals based on USBO501 and USBO502   USBOP6R
3      Chemistry : Practical of USCH501 and USCH502   USCHP06
4      Chemistry : Practical of USCH501 and USCH502   USCHP06

                                           SUBJECT 3 SUBJECT 4 SUBJECT 5  \
0   Zoology : Practical Based on USZO503 and USZO504       NaN       NaN
1       Chemistry : Practical Of USCH503 and USCH504       NaN       NaN
2   Zoology : Practical Based on USZO503 and USZO504       NaN       NaN
3  Mathematics : Practicals based on USMT503 and ...       NaN       NaN
4       Chemistry : Practical Of USCH503 and USCH504       NaN       NaN

  SUBJECT 6
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
Pincode List:
[400706, 410210, 410206, 400709, 701, 400708]

Filtered Data Sample:
                                        INSTITUTE NAME  \
759  Anjuman-I-Islams College of Hotel and Tourism ...
831  Anjuman-I-Islams Institute of Hospitality Mana...
834  Anjuman-I-Islams Institute of Hospitality Mana...
847  Anjuman-I-Islams Institute of Hospitality Mana...
859  Anjuman-I-Islams Institute of Hospitality Mana...

                 STUDENT NAME  GENDER  \
759   MOHAMMAD YUSUF SIDDIQUI    Male
831     DALVI RUNALI PRASHANT  Female
834      FAHAD MOHAMMED SHAFI    Male
847      KHAN FAHIM MOHD AYUB    Male
859  KHERATKAR SARTHAK SANJAY    Male

                                               ADDRESS   PINCODE      MOBILE  \
759  Pocket -A , 26, Sagar CHS Behind Laxmi Dental ...  400709.0  8924933220
831  Sai Srushti Apt Room No 201,Plot No 271 Nerul ...  400706.0  9130359939
834  MA/6/13  COSMOPOLITAN CO-OP SOCIETY , TAKKA TAKKA  410206.0  9773262160
847  Plot No B32 Shop No6,7 Ekta CHS Seawood Sector 23  400706.0  7977357768
859                 10/3  A Type, Sector 13 New Panvel  410206.0  9326434917

                               EMAIL                           COURSE  \
759  siddiquiyousuf.www.ys@gmail.com  T.Y.B.Sc. (Hospitality Studies)
831           Runalidalvi9@gmail.com  T.Y.B.Sc. (Hospitality Studies)
834         fahadfahad5696@gmail.com  T.Y.B.Sc. (Hospitality Studies)
847         khanfaheem7920@gmail.com  T.Y.B.Sc. (Hospitality Studies)
859    sarthak619kheratkar@gmail.com  T.Y.B.Sc. (Hospitality Studies)

                                 SUBJECT 1 SUBJECT 2 SUBJECT 3 SUBJECT 4  \
759  Rooms Division Management(Practical).       NaN       NaN       NaN
831  Rooms Division Management(Practical).       NaN       NaN       NaN
834  Rooms Division Management(Practical).       NaN       NaN       NaN
847  Rooms Division Management(Practical).       NaN       NaN       NaN
859  Rooms Division Management(Practical).       NaN       NaN       NaN

    SUBJECT 5 SUBJECT 6
759       NaN       NaN
831       NaN       NaN
834       NaN       NaN
847       NaN       NaN
859       NaN       NaN

Filtered data saved to: D:\data\filtered_data.xlsx